name: Run backend Tests

on:
  push:
    paths: -"server/**"
  pull_request:
    paths: -"server/**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server
    steps:
      - name: checkout code
        uses: action/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install dependency
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: pytest --tb=short
